language: generic
deploy:
  provider: releases
  secure: VhTwD77Rzi1LraW39GB8D8oCIQmB1f34cm7G0l9JsbMAOTR8wXPtPeFgNXV18WAok/n1hgaco4EyO/EWG+VHJnNHAeZuIrVcxkG+8R5H2DP+OOdvU2zmU5/Hi7VH6Vs/Y0qmi3TFs1Lep2UCsGpLwMAUZNXFaP/ORmO8MszbHoXNG1Ldz3B9UaipKPpI2AcLdaCSykl9D9sVaaXUzaF78sr1uvzTx+4Yi7VN3TXXOWBqDPyPR8LmEgV3Ix4MAVsF8cAosoBzPJO9NcOc3JL2ptiAnDerbnH3REC0TSwl4OuzyrPorzWFff5FTQ7RdwRoLyqHkWwJvnfLuL9KsWeoHvF7ktDkrLM4nzQw64jYd4GQbpayNsfQc5f8q2H+pv9eLf+L3EDaoNqyCAoFu60MbJkssnpgd5hjR9LuM1joieYNfZgSAx2cw0kIYltwKFEq/QA+hzzZVQp5Q4QtahP5rlXkcjcbS2aSKqUpI9y2541+LR0te4Qw9ozpxGa+zGF/KPX/ubL3x2iTx4yQAcTk3HgIEOJjZ6iLO5xtZXTP6fY7V2rf43ZYw//99fO+VtzYPiPj/DGcVqBZNz0gHO93I+p7dYMDEp6Nexw2gfJyF2LPcthmKVtQeSYd+12ivEwzYdX1NArZ30+f3LqD7XBLzCHCT0+gykAWFUWXs/qiCQg=
  file:
  - cretes-cli.zip
  skip_cleanup: true
  on:
    tags: true
sudo: required
dist: trusty
os:
- linux
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
env:
  matrix:
  - CLI_VERSION=Latest
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0
branches:
  only:
  - master
  - dev
before_install:
- export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
- curl -L --create-dirs https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh
  -o ./scripts/obtain/install-dotnet.sh
- find ./scripts -name "*.sh" -exec chmod +x {} \;
- sudo bash ./scripts/obtain/install-dotnet.sh --version "$CLI_VERSION" --install-dir
  "$DOTNET_INSTALL_DIR" --no-path
- export PATH="$DOTNET_INSTALL_DIR:$PATH"
script:
- dotnet restore
- dotnet test ./test/Certes.Tests/project.json
- dotnet pack -c release -o ./build/nuget ./src/Certes/project.json
- dotnet publish -f netcoreapp1.0 -c release -o ./build/cli/bin ./src/Certes.Cli/project.json
- find ./build/cli -path '*/.*' -prune -o -type f -print | zip "$TRAVIS_BUILD_DIR/cretes-cli.zip"
  -@
