language: csharp
mono: none
dotnet: 2.0.0
env:
  matrix:
    - CLI_VERSION=Latest
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 0
branches:
  only:
    - master
    - beta
    - preview
    - release
script:
  - dotnet restore
  - dotnet build --configuration Release --framework netcoreapp1.0 test/Certes.Tests/Certes.Tests.csproj
  - dotnet build --configuration Release --framework netcoreapp2.0 test/Certes.Tests/Certes.Tests.csproj
  - dotnet build --configuration Release --framework netcoreapp1.0 test/Certes.Tests.Integration/Certes.Tests.Integration.csproj
  - dotnet build --configuration Release --framework netcoreapp2.0 test/Certes.Tests.Integration/Certes.Tests.Integration.csproj
  - cd test/Certes.Tests/
  - dotnet minicover instrument --workdir ../../ --assemblies test/Certes.Tests/**/bin/**/*.dll --sources src/**/*.cs
  - dotnet xunit -nobuild -framework netcoreapp1.0 -fxversion 2.0.5
  - dotnet xunit -nobuild -framework netcoreapp2.0 -fxversion 2.0.5
  - dotnet minicover opencoverreport --workdir ../../ --output unit-coverage.xml
  - cd ../../
  - bash <(curl -s https://codecov.io/bash) -f unit-coverage.xml -F unit
