version: 1.0.0-{build}
build:
  verbosity: minimal

branches:
  # whitelist
  only:
    - master
    - dev

install:

build_script:
  - dotnet restore
  - dotnet test ./test/Certes.Tests/project.json
  - dotnet pack -c release -o ./build/nuget ./src/Certes/project.json
  - dotnet publish -f netcoreapp1.0 -c release -o ./build/cli/bin ./src/Certes.Cli/project.json

test: off

configuration: Release

deploy:
  release: certes-v$(appveyor_build_version)
  description: 'Certes v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
  artifact:
    - /build\/nuget\/.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: master
    #appveyor_repo_tag: true
