version: 1.0.{build}
build:
  verbosity: minimal

branches:
  # whitelist
  only:
    - master
    - dev

install:

build_script:
  - dotnet restore
  - dotnet test
  - dotnet pack -c release -o ./build/nuget ./src/Certes/project.json
  - dotnet publish -f netcoreapp1.0 -c release -o ./build/cli/bin ./src/Certes.Cli/project.json

test: off

configuration: Release
