version: 1.0.5.{build}
build:
  verbosity: minimal
  project: Certes.sln

skip_tags: true
image: Visual Studio 2017

skip_commits:
  files:
  - '*.md'

branches:
  # whitelist
  only:
    - master
    - dev

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '${CERTES_PACKAGE_VERSION}'

init:
  - git config --global core.autocrlf input
  - ps: $packageVersion = if ($env:APPVEYOR_REPO_BRANCH -eq "master") { "$($env:appveyor_build_version)" } else { "$($env:appveyor_build_version)-$($env:APPVEYOR_REPO_BRANCH)" }
  - ps: $env:CERTES_PACKAGE_VERSION = $packageVersion
#  - ps: $env:CERTES_PACKAGE_VERSION = $env:appveyor_build_version

install:

before_build:
  - cmd: nuget restore Certes.sln

build_script:
  - msbuild -t:src\Certes
  - msbuild -t:src\Certes:pack -p:PackageVersion="%CERTES_PACKAGE_VERSION%"
  - msbuild -t:src\Certes_Cli
  - msbuild -t:src\Certes_Cli:Publish
  - ps: '"dotnet %~dp0bin/Certes.Cli.dll %* " | Set-Content .\src\Certes.Cli\bin\$($env:CONFIGURATION)\netcoreapp1.0\publish\certes.bat'
  - 7z a build\certes-cli.zip .\src\Certes.Cli\bin\%CONFIGURATION%\netcoreapp1.0\publish\*.* -r

#test: off
test_script:
  - dotnet test ./test/Certes.Tests/Certes.Tests.csproj
  
configuration: Release

artifacts:
    - path: src/Certes/bin/$(CONFIGURATION)/Certes.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg
      
    - path: build\certes-cli.zip
      name: cli

deploy:
  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: true
    prerelease: true
    on:
      branch: dev

  - provider: NuGet
    #server: http://www.nuget.org/api/v2/package                  # remove to push to NuGet.org
    api_key:
      secure: enjdo7AiXKaGhj8NC2k3wjQ9mGlU1jxABzG6tuphpM7dNaazlrSlvwR2H1kC4kr+
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg
    on:
      branch: master

  - provider: NuGet
    server: https://www.myget.org/F/dymetis/api/v2/package
    api_key:
      secure: RSdqUIwRSn8DI5xaa4iWBzOtYU6y3K9JRh07myQpAIRf5IhlwsZpFsnQOpCg1g7J
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg
    on:
      branch: dev
