name: Certes nightly publish (build and publish master)
on:
  push:
    branches: [ master ]
    
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: action-minver
      uses: thefringeninja/action-minver@2.0.0-preview1
      id: version
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.402'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./src/Certes/Certes.csproj --configuration Release --no-restore
    - name: Pack package
      run: dotnet pack ./src/Certes/Certes.csproj -c Release --no-build -p:PackageVersion=${{ steps.version.outputs.version }} -p:PackageID=Nightly-Certes -p:Title="Unstable master build of Certes ACME Client"
    - name: Publish
      run: dotnet nuget push ./src/Certes/bin/Release/*.nupkg --skip-duplicate -s http://nuget.org/ -k ${{secrets.NUGET_PUBLISH_KEY}}
